// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomStatus } from "./AtomStatus";
import type { AtomType } from "./AtomType";
import type { Origin } from "./Origin";

export type Atom = { id: string, capture_id: string, run_id: string | null, text: string, atom_type: AtomType, confidence: number | null, quote: string | null, 
/**
 * UTF-16 offsets into the capture text.
 */
span_start: number | null, span_end: number | null, origin: Origin, status: AtomStatus, created_at: string, updated_at: string, };
