// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Atom } from "./Atom";
import type { LinkView } from "./LinkView";

export type AtomView = { atom: Atom, 
/**
 * Suggested and confirmed links (rejected links are hidden but kept).
 */
links: Array<LinkView>, };
