// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Initial atom vocabulary (docs/PRODUCT.md). Keep it small.
 */
export type AtomType = "spark" | "project" | "feature" | "task" | "question" | "research" | "reference" | "decision" | "problem" | "someday";
