// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomView } from "./AtomView";
import type { Capture } from "./Capture";
import type { ProcessingState } from "./ProcessingState";
import type { ProjectSuggestion } from "./ProjectSuggestion";

export type CaptureView = { capture: Capture, state: ProcessingState, last_error: string | null, atoms: Array<AtomView>, pending_suggestions: Array<ProjectSuggestion>, 
/**
 * `provider/model` of the latest successful analysis, for provenance.
 */
interpreted_by: string | null, };
