// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Capture = { id: string, 
/**
 * Exactly what the user submitted. Never rewritten.
 */
text: string, source: string, captured_at: string, deleted_at: string | null, };
