// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureView } from "./CaptureView";
import type { ProcessingStatus } from "./ProcessingStatus";
import type { ProjectSuggestion } from "./ProjectSuggestion";
import type { ProjectSummary } from "./ProjectSummary";
import type { RecurringItem } from "./RecurringItem";

export type HomeData = { recent: Array<CaptureView>, active_projects: Array<ProjectSummary>, recurring: Array<RecurringItem>, pending_suggestions: Array<ProjectSuggestion>, processing: ProcessingStatus, };
