// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProcessingStatus = { enabled: boolean, provider: string, 
/**
 * Set when processing can't run (missing key/model, disabled).
 */
blocked_reason: string | null, queued: number, running: number, failed: number, };
