// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * UX.md processing states. A model failure is never a capture failure.
 */
export type ProcessingState = "saved" | "analyzing" | "processed" | "needs_retry";
