// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project";
import type { SynthesisView } from "./SynthesisView";
import type { TimelineEntry } from "./TimelineEntry";

export type ProjectPage = { project: Project, timeline: Array<TimelineEntry>, synthesis: SynthesisView | null, };
