// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project";

export type ProjectSummary = { project: Project, confirmed_atoms: number, suggested_atoms: number, last_activity: string | null, };
