// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Momentum } from "./Momentum";

export type Project = { id: string, name: string, description: string, momentum: Momentum, created_at: string, updated_at: string, };
