// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Atom } from "./Atom";
import type { Capture } from "./Capture";

export type RelatedAtom = { atom: Atom, capture: Capture, similarity: number, };
