// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project";

export type RespondOutcome = { 
/**
 * Project whose momentum was set to active (make_active).
 */
activated_project: Project | null, 
/**
 * make_active on an atom with no project: UI should offer to create one.
 */
needs_project: boolean, };
