// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResurfaceWeights = { dormancy: number, recurrence: number, active_project: number, open_question: number, exploration: number, not_now_penalty: number, };
