// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Atom } from "./Atom";
import type { Capture } from "./Capture";
import type { LinkView } from "./LinkView";
import type { ScoreTerm } from "./ScoreTerm";

export type ResurfaceCard = { event_id: string, atom: Atom, capture: Capture, projects: Array<LinkView>, score: number, 
/**
 * Human-readable reason, from the largest positive term.
 */
reason: string, terms: Array<ScoreTerm>, };
