// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScoreTerm = { name: string, 
/**
 * Weighted contribution to the score.
 */
value: number, explanation: string, };
