// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomType } from "./AtomType";
import type { MatchKind } from "./MatchKind";
import type { SearchKind } from "./SearchKind";

export type SearchResult = { kind: SearchKind, id: string, capture_id: string, text: string, 
/**
 * Lexical snippet with `[` `]` markers around hits, when available.
 */
snippet: string | null, atom_type: AtomType | null, captured_at: string, matched: MatchKind, score: number, };
