// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchResult } from "./SearchResult";

export type SearchResponse = { results: Array<SearchResult>, semantic_used: boolean, 
/**
 * Why semantic search was skipped (offline, no embedder, ...).
 */
semantic_note: string | null, };
