// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind";
import type { ResurfaceWeights } from "./ResurfaceWeights";

export type Settings = { 
/**
 * Master switch for AI processing ("remote processing off" ⇒ jobs stay queued).
 */
processing_enabled: boolean, provider: ProviderKind, 
/**
 * OpenRouter model id for analysis/linking/synthesis, e.g. "vendor/model".
 * PLACEHOLDER: intentionally empty until a default is chosen (TASKS §6).
 */
analyzer_model: string, 
/**
 * OpenRouter embedding model id. Empty ⇒ semantic features disabled.
 * PLACEHOLDER: intentionally empty until a default is chosen (TASKS §8).
 */
embedding_model: string, 
/**
 * Route only to zero-data-retention endpoints (narrows model choice).
 */
openrouter_zdr: boolean, 
/**
 * Cosine similarity at which two atoms count as "the same idea again".
 * PLACEHOLDER: depends on the embedding model; tune during dogfooding.
 */
similarity_threshold: number, resurface_weights: ResurfaceWeights, 
/**
 * Don't resurface an item again within this many days.
 */
resurface_suppress_days: number, 
/**
 * "Not now" penalty window.
 */
not_now_days: number, backups_to_keep: number, trash_retention_days: number, 
/**
 * Global capture hotkey (Tauri accelerator syntax).
 */
global_shortcut: string, };
