// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeySource } from "./KeySource";
import type { Settings } from "./Settings";

/**
 * Settings plus derived, read-only facts for the Settings screen.
 */
export type SettingsView = { settings: Settings, api_key_source: KeySource, 
/**
 * Where embeddings are stored for the current settings.
 */
embedding_model_id: string | null, data_dir: string, };
