// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountRow } from "./CountRow";

export type Stats = { total_captures: number, 
/**
 * Last 8 ISO weeks, oldest first, labelled by week start (YYYY-MM-DD).
 */
captures_per_week: Array<CountRow>, total_atoms: number, 
/**
 * Atoms the user edited, added or rejected.
 */
corrected_atoms: number, atom_correction_rate: number | null, links_by_status: Array<CountRow>, link_confirm_rate: number | null, resurfacing_responses: Array<CountRow>, };
