// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSynthesis } from "./ThreadSynthesis";

export type SynthesisView = { body: ThreadSynthesis, source_capture_ids: Array<string>, model: string | null, created_at: string, 
/**
 * Newer linked captures exist than the synthesis was based on.
 */
stale: boolean, };
