// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadSynthesis = { summary: string, open_questions: Array<string>, possible_next_actions: Array<string>, decisions: Array<string>, changed_assumptions: Array<string>, };
