// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomView } from "./AtomView";
import type { Capture } from "./Capture";

export type TimelineEntry = { capture: Capture, 
/**
 * Atoms of this capture linked (suggested or confirmed) to the project.
 */
atoms: Array<AtomView>, };
